// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxZ40Oj7xe1fByBdlSCCBUTUhMPLGtBk',
    appId: '1:382986159945:web:0e65a782116e3ef07bbc98',
    messagingSenderId: '382986159945',
    projectId: 'electricity-monitor-9140f',
    authDomain: 'electricity-monitor-9140f.firebaseapp.com',
    databaseURL: 'https://electricity-monitor-9140f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'electricity-monitor-9140f.firebasestorage.app',
    measurementId: 'G-KMFX7KSHHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhEOK95WZzzTzDevymq0IRb4kb0j5dRzs',
    appId: '1:382986159945:android:39666f4389ba93bb7bbc98',
    messagingSenderId: '382986159945',
    projectId: 'electricity-monitor-9140f',
    databaseURL: 'https://electricity-monitor-9140f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'electricity-monitor-9140f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbuo1JrJ4ydI0rWRxubc1jAP12ZK9WCDs',
    appId: '1:382986159945:ios:5033ea40a7e31e7f7bbc98',
    messagingSenderId: '382986159945',
    projectId: 'electricity-monitor-9140f',
    databaseURL: 'https://electricity-monitor-9140f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'electricity-monitor-9140f.firebasestorage.app',
    iosBundleId: 'com.example.mobileEMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbuo1JrJ4ydI0rWRxubc1jAP12ZK9WCDs',
    appId: '1:382986159945:ios:5033ea40a7e31e7f7bbc98',
    messagingSenderId: '382986159945',
    projectId: 'electricity-monitor-9140f',
    databaseURL: 'https://electricity-monitor-9140f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'electricity-monitor-9140f.firebasestorage.app',
    iosBundleId: 'com.example.mobileEMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFxZ40Oj7xe1fByBdlSCCBUTUhMPLGtBk',
    appId: '1:382986159945:web:c462f37ece14e3fb7bbc98',
    messagingSenderId: '382986159945',
    projectId: 'electricity-monitor-9140f',
    authDomain: 'electricity-monitor-9140f.firebaseapp.com',
    databaseURL: 'https://electricity-monitor-9140f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'electricity-monitor-9140f.firebasestorage.app',
    measurementId: 'G-7FT0KGQK73',
  );

}